version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      eslint-group:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
      typescript-group:
        patterns:
          - "typescript"
          - "ts-*"
      prettier-group:
        patterns:
          - "prettier*"
      stylelint-group:
        patterns:
          - "stylelint*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "03:00"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
