name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE (#$NUMBER)"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
categories:
  - title: "🚀 Features"
    labels:
      - "minor"
  - title: "🐛 Bug Fixes"
    labels:
      - "patch"
      - "bugfix"
  - title: "🧰 Maintenance"
    labels:
      - "dependencies"
template: |
  ## What's Changed

  $CHANGES
